baseURL = "https://adventures.jgosmann.de/"
languageCode = "en-us"
title = "Jan's outdoor adventures"
timeout = 30000
DefaultContentLanguage = "en"

[languages.en]
weight = 1

[languages.de]
weight = 2

[module]
  [[module.mounts]]
    source = "node_modules/flag-icon-css/flags"
    target = "static/flags"

  [[module.mounts]]
    source = "lib"
    target = "static"

[params]
mainSections = ["posts"]

[imaging]
resampleFilter = "CatmullRom"
quality = 90
anchor = "center"

[blackfriday]
fractions = false
