baseURL = "https://adventures.jgosmann.de/"
languageCode = "en-us"
title = "Jan's outdoor adventures"
timeout = 30000

[params]
mainSections = ["posts"]

[imaging]
resampleFilter = "CatmullRom"
quality = 90
anchor = "center"
