name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check:
          - name: Type check
            run: yarn run type-check
          - name: Lint
            run: yarn run lint
          - name: Test
            run: yarn test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --non-interactive

      - name: ${{ matrix.check.name }}
        run: ${{ matrix.check.run }}
        env:
          CI: true

  E2E:
    runs-on: ubuntu-latest
    needs: Node

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --non-interactive
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - run: echo '{"mapbox":""}' > access-tokens.json
      - name: Delete non-required files to speed up build
        working-directory: ./content/posts
        run: find . -maxdepth 1 -type d -name ! -name '*190716-squamish' -name '.' -exec rm -r {} +
      - name: Start Gtasby development mode
        run: |
          npx gatsby develop &
          for i in {1..60}; do
            echo "Waiting 5 seconds"
            sleep 5
            if curl -I http://localhost:8000/; then
              echo "Gatsby ready"
              break
            fi
          done
          if ! curl -I http://localhost:8000/; then
            echo "Not ready after 5 minutes, aborting."
            exit 1
          fi
      - run: curl --fail http://localhost:8000/search.json --output ./search.json
      - run: docker compose up --wait -d
      - run: docker compose logs
        if: always()
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

  Chromatic:
    runs-on: ubuntu-latest
    needs: Node
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile --non-interactive

      - name: Publish to Chromatic for visual verification
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
