name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  Node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        check:
          - name: Type check
            run: yarn run type-check
          - name: Lint
            run: yarn run lint
          - name: Test
            run: yarn test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - run: yarn install --frozen-lockfile --non-interactive

      - name: ${{ matrix.check.name }}
        run: ${{ matrix.check.run }}
        env:
          CI: true

  Chromatic:
    runs-on: ubuntu-latest
    needs: Node
    if: github.ref == 'refs/heads/develop'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - run: yarn install --frozen-lockfile --non-interactive

      - name: Publish to Chromatic for visual verification
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
